config/routes.rb
Rails.application.routes.draw do
  resources :startups
  get 'pages/home'

  get 'pages/add'

  root 'startups#index'

end

app/models/startup.rb
class Startup < ActiveRecord::Base
  validates :name, presence: true
  validates :url, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def add
  end
end

app/controllers/startups_controller.rb
class StartupsController < ApplicationController
  before_action :set_startup, only: [:show, :edit, :update, :destroy]

  # GET /startups
  # GET /startups.json
  def index
    @startups = Startup.all
  end

  # GET /startups/1
  # GET /startups/1.json
  def show
  end

  # GET /startups/new
  def new
    @startup = Startup.new
  end

  # GET /startups/1/edit
  def edit
  end

  # POST /startups
  # POST /startups.json
  def create
    @startup = Startup.new(startup_params)

    respond_to do |format|
      if @startup.save
        format.html { redirect_to @startup, notice: 'Startup was successfully created.' }
        format.json { render :show, status: :created, location: @startup }
      else
        format.html { render :new }
        format.json { render json: @startup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /startups/1
  # PATCH/PUT /startups/1.json
  def update
    respond_to do |format|
      if @startup.update(startup_params)
        format.html { redirect_to @startup, notice: 'Startup was successfully updated.' }
        format.json { render :show, status: :ok, location: @startup }
      else
        format.html { render :edit }
        format.json { render json: @startup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /startups/1
  # DELETE /startups/1.json
  def destroy
    @startup.destroy
    respond_to do |format|
      format.html { redirect_to startups_url, notice: 'Startup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_startup
      @startup = Startup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def startup_params
      params.require(:startup).permit(:name, :description, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/startups_helper.rb
module StartupsHelper
end

app/views/layouts/_google_analytics.html.erb
<% if Rails.env == "production"  %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-65428110-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StartupGraveyard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '<span class="navbar-brand" href="#">Startup Graveyard</span>'.html_safe, root_path %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
      
        <%= link_to'<button type="button" class="btn btn-default navbar-btn"> <span class="glyphicon glyphicon-plus" aria-hidden="true"></span></button>'.html_safe, new_startup_path %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="jumbotron">
  <div class="container">
    <h2>Startup Graveyard <small>The resting place for startups' code</small></h2>
    <p>Links to the repos of startups that have died or gone dark. Check the licensing before using.</p>
  </div>
</div>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/pages/add.html.erb
<h1>Pages#add</h1>
<p>Find me in app/views/pages/add.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/startups/_form.html.erb
<%= form_for(@startup) do |f| %>
  <% if @startup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@startup.errors.count, "error") %> prohibited this startup from being saved:</h2>

      <ul>
      <% @startup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<form>
  <div class="form-group">
    <label><%= f.label :name %></label>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <label><%= f.label :description %></label>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <label><%= f.label :url %></label>
    <%= f.text_field :url, class: "form-control" %>
  </div>
     <%= f.submit 'Submit', :class => 'btn btn-primary btn-large' %>
    <%= link_to "Cancel", :back, {:class=>"btn btn-default"} %>
</form>
<% end %>

app/views/startups/edit.html.erb
<h1>Edit Startup</h1>

<%= render 'form' %>

app/views/startups/index.html.erb
<p id="notice"><%= notice %></p>


  <!-- Table -->
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody">
    <% @startups.each do |startup| %>
      <tr>
        <td><%= link_to startup.name, startup %></td>
        <td><%= startup.description %></td>
        <td><a href="<%= startup.url %>"><%= startup.url %></a></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/startups/new.html.erb
<h2>Add Startup</h2>

<%= render 'form' %>

app/views/startups/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @startup.name %></td>
        <td><%= @startup.description %></td>
        <td><a href="<%= @startup.url %>"><%= @startup.url %></a></td>
      </tr>
  </tbody>
</table>

<p class="one">
<%= link_to 'Edit', edit_startup_path(@startup), :class => 'btn btn-default' %>
<%= link_to 'Back', startups_path, :class => 'btn btn-default' %> 
<%= link_to 'Delete', @startup, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger'%>
</p>